import { sceneArt, stageGuide } from './act-art';
import { routes, methods, sources, type Choice } from '../data/act';
const KEY='zuoxiqiu-act-v1';
type State={version:1;route:string;step:number;answers:Record<string,number>;seen:string[];remaining:number;duration:number;motion:boolean;ended:boolean;exitFrom?:number};
const root=document.querySelector<HTMLElement>('#act-root')!;
const page=document.querySelector<HTMLElement>('.act-page')!;
const tools=document.querySelector<HTMLElement>('#act-tools')!;
const announce=document.querySelector<HTMLElement>('#act-announcement')!;
let storageOK=true;
let state:State|null=null;
let saved:State|null=null;
let motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
let tick:ReturnType<typeof setInterval>|undefined;
let deadline=0;
const escape=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(label:string,action:string,secondary=false)=>`<button class="act-button ${secondary?'secondary':''}" data-action="${action}">${label}</button>`;
try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(s.version===1&&routes.some(r=>r.id===s.route)&&Number.isInteger(s.step)&&s.step>=0&&s.step<=6&&s.answers&&typeof s.answers==='object'&&!Array.isArray(s.answers)&&Object.entries(s.answers).every(([k,v])=>['0','1','2','3','4','5','6'].includes(k)&&Number.isInteger(v)&&Number(v)>=0&&Number(v)<4)&&Array.isArray(s.seen)&&s.seen.every((x:unknown)=>typeof x==='string'&&x in methods)&&Number.isFinite(s.remaining)&&s.remaining>=0&&s.remaining<=90&&[30,60,90].includes(s.duration)&&typeof s.motion==='boolean'&&typeof s.ended==='boolean'&&(s.exitFrom===undefined||(Number.isInteger(s.exitFrom)&&s.exitFrom>=0&&s.exitFrom<6))){saved=s;motion=s.motion;}else localStorage.removeItem(KEY);}}catch{storageOK=false;}
function persist(){if(!state)return;state.motion=motion;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;}storageNotice();}
function storageNotice(){document.querySelector('#act-storage')!.textContent=storageOK?'选择仅保存在本机，不上传。可随时清除。':'本机存储不可用；仍可继续体验，离开后不会保存。';}
function pause(){if(tick!==undefined){state!.remaining=Math.max(0,(deadline-Date.now())/1000);clearInterval(tick);tick=undefined;persist();}timerPaint();}
function timerPaint(){const out=root.querySelector('output');if(out&&state)out.textContent=`${Math.ceil(state.remaining)} 秒 · ${tick!==undefined?'停留中':state.remaining===0?'这段停留已结束，可以继续或再留一会儿':'未运行'}`;const b=root.querySelector<HTMLElement>('[data-action="timer-toggle"]');if(b)b.textContent=tick!==undefined?'暂停':state?.remaining===0?'重新计时':'开始 / 继续计时';}
function timer(){return `<div class="act-timer"><p class="act-muted">可以停留一会儿，也可以直接继续。计时不代表练习要求。</p><div class="act-timer-controls">${[30,60,90].map(n=>`<button data-duration="${n}" aria-pressed="${state!.duration===n}">${n} 秒</button>`).join('')}</div><output aria-label="剩余停留时间"></output><div class="act-timer-controls"><button data-action="timer-toggle">开始 / 继续计时</button><button data-action="timer-end">结束计时</button></div></div>`;}
const fallback:Choice=['都不太像，先用这个例子','这个例子不完全像你。后面可以继续跟随它，不需要把自己的经历硬放进去。'];
const unsure:Choice=['暂时不清楚','可以暂时不清楚。方向不需要在这一页被整理成一个确定答案。'];
const undecided:Choice=['先不决定','可以先不决定。看见了几种回应，并不等于现在就需要选定一种生活里的行动。'];
const endings:Choice[]=[['理解了一点','这一点理解可以先留着。以后想起时再尝试，不必把生活变成持续的练习检查。'],['还是难受','难受仍在，是你此刻的感受。这里不要求再练一遍来证明有效，你可以结束、休息或寻求支持。'],['不太适合我','这次方式可能不贴近你的处境。可以不用它，也可以寻找更适合的帮助。'],['暂时说不清','不需要现在总结出一个收获。到这里停下也可以。']];
function choices(list:Choice[],step=state!.step){return `<div class="act-choices">${list.map(([label],i)=>`<button class="act-choice" data-choice="${i}" aria-pressed="${state!.answers[step]===i}">${escape(label)}</button>`).join('')}</div><p class="act-feedback" role="status">${escape(list[state!.answers[step]]?.[1]??'')}</p>`;}
function listForStep():Choice[]{const r=routes.find(r=>r.id===state!.route)!;switch(state!.step){case 0:return [...r.choices,fallback];case 1:return [['联系自己的情况','可以在心里联系一件事，不用在这里写下或说明。'],['继续跟随例子','可以把这当作一次方法体验，不必带入私人经历。']];case 2:case 3:return r.exercises[state!.step-2].choices;case 4:return [...r.values,unsure];case 5:return [...r.actions,undecided];default:return endings;}}
function sourceHTML(){return `<div class="act-sources"><p>中文情境、引导和图形为本站原创，参考下列资料中的方法，不复制整套教材。本页不等同于完整心理治疗。</p>${sources.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`).join('')}</div>`;}
function render(focus=true){page.dataset.active=String(!!state);page.dataset.animate=String(focus);page.dataset.scene=state?.route??'entry';page.dataset.step=String(state?.step??0);page.dataset.static=String(!motion);tools.hidden=false;tools.querySelector('[data-global="motion"]')!.textContent=motion?'关闭动效':'启用动效';tools.querySelector('[data-global="motion"]')!.setAttribute('aria-pressed',String(!motion));storageNotice();
if(!state){root.innerHTML=`${saved?`<section class="act-card"><p class="act-kicker">上次停留在这里</p><h2 tabindex="-1">${escape(routes.find(r=>r.id===saved!.route)!.title)}</h2><p>第 ${saved.step+1} 步。计时保持暂停，由你决定是否继续。</p><div class="act-nav">${button('继续上次','resume')}${button('重新开始','restart',true)}</div></section>`:`<p class="act-intro">这是 ACT 方法体验，不作诊断。选一个场景，动手试一次：给担忧加个外框、拆开一叠任务，或在发送消息前留一点间隔。</p><p class="act-muted">每条约十分钟，包含自由停留。可以跳过、暂停或随时结束，无需输入任何文字。</p><div class="act-routes">${routes.map((r,i)=>`<button class="act-route" data-route="${r.id}"><span class="act-kicker">0${i+1} ↗</span>${sceneArt(r.id)}<strong>${r.title}</strong><small>${r.teaser}</small></button>`).join('')}</div>`}`;return;}
const r=routes.find(r=>r.id===state!.route)!;let title='',body='';const step=state.step;
if(step===0){title='先从一个情境开始';body=`<p class="act-body">${r.scene}</p><p class="act-muted">哪一项比较贴近？选择只用于调整回应。</p>${choices(listForStep())}`;}
if(step===1){title='先停在你选的这一点';body=`<p class="act-body">${escape([...r.choices,fallback][state.answers[0]??3][1])}</p><p class="act-body">接下来，可以在心里联系自己的情况，也可以继续跟随这个例子。无需解释全部来由，暂时不愿靠近的经历可以先放着。</p>${choices(listForStep())}`;}
if(step===2||step===3){const e=r.exercises[step-2];if(!state.seen.includes(e.method))state.seen.push(e.method);title=e.title;const touched=state.answers[step]!==undefined;const expanded=step===3&&touched&&(r.id==='starting'||r.id==='urge'||state.answers[step]===0);const guide=stageGuide[r.id];body=`<p class="act-do-now">${step===3?guide[0]:e.prompt}</p><div class="act-playground ${expanded?'is-open':''}">${sceneArt(r.id,expanded)}<div class="act-on-canvas">${choices(e.choices)}</div></div><p class="act-purpose">${step===3?(touched?guide[1]:guide[2]):'选一个注意的落点，再在你身边试一试。页面里的点击只是提示，不会替你完成觉察。'}</p><details class="act-explanation"><summary>这一步具体怎么做？</summary><p class="act-body">${e.body}</p></details><details class="act-stay"><summary>想在这里停留一会儿 · 可选计时</summary>${timer()}</details>`;}
if(step===4){if(!state.seen.includes('values'))state.seen.push('values');title='此刻，比较重视哪一个方向';body=`<p class="act-body">感受可能仍在。带着刚才看到的处境，看看你愿意怎样对待自己、别人和眼前的事情。这些方向可以同时重要，选一个此刻较贴近的就好。它不是对你是什么人的判断，也不要求今后每次都选同一个。</p>${choices(listForStep())}`;}
if(step===5){if(!state.seen.includes('action'))state.seen.push('action');title='一个眼下可行的回应';body=`<p class="act-body">你刚才留意的方向是：${escape([...r.values,unsure][state.answers[4]??3][0])}。下面是几种可能的回应，可能需要付出不同的代价。看看哪一种在此刻的条件下较可行，也可以先不决定。在页面里选择，还不等于已经在生活中做到。</p>${choices(listForStep())}`;}
if(step===6){title=state.ended?'在这里结束，也可以回看':'把方法留在这里';body=`<p class="act-body">这里列出本次页面中接触过的方法。看过、跳过或尝试过，都不代表已经掌握；点选行动，也不等于已经执行。它们可以在需要时再被想起，不必成为生活里另一套检查标准。</p>${state.seen.length?state.seen.map(key=>`<section class="act-method"><h3>${methods[key][0]}</h3><p>${methods[key][1]}</p></section>`).join(''):'<p>这次还没有进入练习。无需补完，也可以直接离开。</p>'}<h3>此刻怎样，都可以留下</h3>${choices(endings)}${sourceHTML()}`;}
root.innerHTML=`<div class="act-topline"><span>${r.title} · ${step+1} / 7</span>${step<6?'<button class="act-link" data-action="end">结束本次体验</button>':''}</div><div class="act-progress" aria-hidden="true">${Array.from({length:7},(_,i)=>`<i class="${i<=step?'current':''}"></i>`).join('')}</div><section class="act-card"><p class="act-kicker">${['进入情境','回应','注意当下','留一点空间','重视的方向','可行的回应','回看方法'][step]}</p><h2 tabindex="-1">${title}</h2><div class="act-stage-body">${![2,3,6].includes(step)?`<div class="act-scene-window">${sceneArt(r.id,step>=4)}<p class="act-scene-caption">${({thoughts:'明天还没来，你先坐在这里。',starting:'桌上的事情还在，可以从一处开始。',urge:'消息还没有发出。这里容得下一点等待。',feeling:'感受在这里，生活也在这里。'} as Record<string,string>)[r.id]}</p></div>`:''}<div class="act-narrative">${body}</div></div><nav class="act-nav" aria-label="体验导航">${step>0?button('上一步','back',true):button('返回四个入口','home',true)}${step<6?button('继续','next'):button('再次选择一种状态','home')}${step===2||step===3?'<button class="act-link" data-action="skip">跳过练习</button>':''}${step===6?'<a class="act-link" href="/">回到首页</a>':''}</nav></section>`;
persist();timerPaint();if(focus)root.querySelector<HTMLElement>('h2')?.focus({preventScroll:true});}
root.addEventListener('click',event=>{const target=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!target)return;
if(target.dataset.route){pause();state={version:1,route:target.dataset.route,step:0,answers:{},seen:[],remaining:60,duration:60,motion,ended:false};saved=null;render();page.scrollIntoView({block:'start'});return;}
const action=target.dataset.action;
if(action==='resume'){state=saved;saved=null;render();return;}
if(action==='restart'||action==='home'){pause();state=null;saved=null;try{localStorage.removeItem(KEY);}catch{}render();root.querySelector<HTMLButtonElement>('button')?.focus();return;}
if(!state)return;
if(target.dataset.choice!==undefined){const i=Number(target.dataset.choice),step=state.step;const running=tick!==undefined;pause();if(state.answers[step]!==i){for(const key of Object.keys(state.answers))if(Number(key)>step)delete state.answers[key];}state.answers[step]=i;render(false);root.querySelector<HTMLButtonElement>(`[data-choice="${i}"]`)?.focus({preventScroll:true});if(running)announce.textContent='计时已暂停，可以继续计时。';return;}
if(target.dataset.duration){pause();state.duration=Number(target.dataset.duration);state.remaining=state.duration;render(false);root.querySelector<HTMLButtonElement>(`[data-duration="${state.duration}"]`)?.focus();return;}
if(action==='timer-toggle'){if(tick!==undefined)pause();else{if(state.remaining<=0)state.remaining=state.duration;deadline=Date.now()+state.remaining*1000;tick=setInterval(()=>{if(!state)return;state.remaining=Math.max(0,(deadline-Date.now())/1000);timerPaint();if(state.remaining===0){pause();announce.textContent='这段停留已结束。页面会留在这里，由你决定何时继续。';}},200);persist();timerPaint();}return;}
if(action==='timer-end'){pause();state.remaining=0;persist();timerPaint();return;}
pause();if(action==='end'){state.exitFrom=state.step;state.ended=true;state.step=6;}else if(action==='back'){state.step=state.ended?(state.exitFrom??0):Math.max(0,state.step-1);state.ended=false;}else if(action==='next'||action==='skip'){if(action==='skip')for(const key of Object.keys(state.answers))if(Number(key)>=state.step)delete state.answers[key];state.step=Math.min(6,state.step+1);}state.remaining=state.duration;render();root.scrollIntoView({behavior:'instant',block:'start'});
});
tools.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-global]');if(!b)return;if(b.dataset.global==='clear'){pause();try{localStorage.removeItem(KEY);}catch{}state=null;saved=null;render();announce.textContent='本机进度已清除。';}else{motion=!motion;if(state)state.motion=motion;if(saved){saved.motion=motion;try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{storageOK=false;}}render(false);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',pause);window.addEventListener('blur',pause);matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){motion=false;render(false);}});render(false);
